name: TESTS

on: push

jobs:
    tests:
        name: TESTS
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Test
              run: npm run coverage # or npm run test
