name: TESTS

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  tests:
    name: TESTS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Test
        run: npm run test
